spring:
  profiles:
    active:
      - dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: wndyd4318@gmail.com
    password: mjti jnrr azjo idwn
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true